version: '2'
services:
  elm:
    build:
      context: .
      dockerfile: Dockerfile-elm
    volumes:
      - .:/code
  web:
    build: .
    command: gunicorn jarbas.wsgi --reload --bind 0.0.0.0:8001 --workers 4
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True

