version: '2'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=jarbas
      - POSTGRES_DB=jarbas
  elm:
    build:
      context: .
      dockerfile: Dockerfile-elm
    volumes:
      - .:/code
  web:
    build: .
    command: gunicorn jarbas.wsgi --reload --bind 0.0.0.0:8001 --workers 4
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=lets-rock
      - DATABASE_URL=postgres://jarbas:mysecretpassword@db/jarbas
    depends_on:
      - db

