FROM node:6.9.1
RUN mkdir /build
WORKDIR /build
COPY elm-package.json elm-package.json
COPY package.json package.json
COPY gulpfile.js gulpfile.js
COPY jarbas jarbas
RUN npm install
CMD npm run assets && \
    cp jarbas/frontend/static/app.js /code/jarbas/frontend/static/app.js
